controller_frequency: 10.0 #cmd_velトピック（前進速度と回頭速度）をpublishする周波数。
planner_patience: 5.0 #有効なパスが見つからなかった時にプランナーがどれだけ待機するか。
controller_patience: 3.0 #指定秒，停止状態が継続した場合Recovery行動に移行する
planner_frequency: 0.0 #global plannerがグローバルパスを計算する頻度。0.0に設定すると、最初にゴールが設定された時のみにグローバルパスが計算される。
shutdown_costmaps: true #障害物をコストマップに残し続けておくか。
oscillation_timeout: 10.0 #指定秒、振動行動が継続した場合にリカバリに移行する。
oscillation_distance: 0.2 #ロボットが振動していないと判断するための移動距離[m]。