map_update_interval: 1.0 #地図の更新間隔[s]
temporalUpdate: 1.0 #最後に処理されたスキャンが指定秒の更新時間より古い場合、スキャンを処理します。0より小さい値を設定すると、時間ベースの更新はオフになる。
xmin: -4.0 #初期マップサイズ[m]
xmax:  4.0 #初期マップサイズ[m]
ymin: -4.0 #初期マップサイズ[m]
ymax:  4.0 #初期マップサイズ[m]
