obstacle_range: 5.0 #ロボットとの距離がobstacle_range以下のオブジェクトは障害物としてみなし、コストマップに反映する。
raytrace_range: 7.0 #ロボットとの距離がraytrace_range以下のオブジェクトが検出された場合、そのオブジェクトの内側のコストマップの障害物がクリアされる。
#footprint: [[x0, y0], [x1, y1], [x2, y2], [x3, y3]]
footprint: [[0.17, 0.17], [-0.17, 0.17], [-0.17, -0.17], [0.17, -0.17]] #ロボットの形状を多角形で指示することができる。footprintの形状に応じてコストマップのdefinitery in collisionとpossibly in collisionの径が決定される。
#robot_radius: ir_of_robot
inflation_radius: 0.1 #コストマップを膨張させる距離
observation_sources: laser_scan_sensor #センサ情報の名前空間を指定する。

laser_scan_sensor: {sensor_frame: beego/hokuyo_link, data_type: LaserScan, topic: beego/scan, marking: true, clearing: true}
#センサ情報の設定 sensor_frame:センサの座標系の指定。 
#data_type:センサから送られてくるデータタイプ。LaserScan、PointCloud、PointCloud2のいずれかが指定できる。
#topic:コストマップに使用されるセンサのトピック
#marking:このセンサデータを障害物としてコストマップに反映させるか。
#clearing:センサデータを障害物のクリアに使うか。 
