local_costmap:
  global_frame: beego/odom #ロボットから得られるオドメトリ情報のフレーム。
  robot_base_frame: beego/base_link #ロボットのフレーム。
  update_frequency: 5.0 #local_costmapを更新する頻度。（Hz）
  publish_frequency: 2.0 #rvizで可視化するためにcostmapなどの情報をpublishする頻度。[Hz]
  static_map: false #map_serverが提供するマップに基づいてコストマップ自身を初期化するかどうか
  rolling_window: true #コストマップをロボットを中心に表示するかどうか。
  width: 10.0 #ローカルコストマップを計算する範囲。[m]
  height: 10.0 #ローカルコストマップを計算する範囲。[m]
  resolution: 0.05 #ローカルコストマップの解像度。[m/pixel]
